name: "CI"
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4.1.1

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Check JsonSchema
        run: |
          nix develop --command std //phishing/entrypoints/check:run

      - name: Check Vast Integration and task
        run: |
          nix run .#x86_64-linux.vast.entrypoints.check

      - name: Build Doc
        run: nix develop .#doc --command mdbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: ./docs/book
