name: "CI"
on:
  push:
    branches: [main]
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Devshell
        run: |
          nix develop ./nix/std --command 'echo hello'
